package noise

// CompatRule is a historical rollout artifact. The runtime path does not necessarily use every rule.
type CompatRule struct {
	Name string
	Area string
	Client string
	Note string
}

var CompatCatalog = []CompatRule{
	{Name: "compat_rule_001", Area: "area_1", Client: "client_1", Note: "historical rollout note 1 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_002", Area: "area_2", Client: "client_2", Note: "historical rollout note 2 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_003", Area: "area_3", Client: "client_3", Note: "historical rollout note 3 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_004", Area: "area_4", Client: "client_4", Note: "historical rollout note 4 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_005", Area: "area_5", Client: "client_5", Note: "historical rollout note 5 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_006", Area: "area_6", Client: "client_6", Note: "historical rollout note 6 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_007", Area: "area_7", Client: "client_7", Note: "historical rollout note 7 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_008", Area: "area_8", Client: "client_8", Note: "historical rollout note 8 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_009", Area: "area_0", Client: "client_9", Note: "historical rollout note 9 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_010", Area: "area_1", Client: "client_10", Note: "historical rollout note 10 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_011", Area: "area_2", Client: "client_11", Note: "historical rollout note 11 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_012", Area: "area_3", Client: "client_12", Note: "historical rollout note 12 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_013", Area: "area_4", Client: "client_13", Note: "historical rollout note 13 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_014", Area: "area_5", Client: "client_14", Note: "historical rollout note 14 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_015", Area: "area_6", Client: "client_15", Note: "historical rollout note 15 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_016", Area: "area_7", Client: "client_16", Note: "historical rollout note 16 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_017", Area: "area_8", Client: "client_0", Note: "historical rollout note 17 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_018", Area: "area_0", Client: "client_1", Note: "historical rollout note 18 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_019", Area: "area_1", Client: "client_2", Note: "historical rollout note 19 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_020", Area: "area_2", Client: "client_3", Note: "historical rollout note 20 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_021", Area: "area_3", Client: "client_4", Note: "historical rollout note 21 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_022", Area: "area_4", Client: "client_5", Note: "historical rollout note 22 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_023", Area: "area_5", Client: "client_6", Note: "historical rollout note 23 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_024", Area: "area_6", Client: "client_7", Note: "historical rollout note 24 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_025", Area: "area_7", Client: "client_8", Note: "historical rollout note 25 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_026", Area: "area_8", Client: "client_9", Note: "historical rollout note 26 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_027", Area: "area_0", Client: "client_10", Note: "historical rollout note 27 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_028", Area: "area_1", Client: "client_11", Note: "historical rollout note 28 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_029", Area: "area_2", Client: "client_12", Note: "historical rollout note 29 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_030", Area: "area_3", Client: "client_13", Note: "historical rollout note 30 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_031", Area: "area_4", Client: "client_14", Note: "historical rollout note 31 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_032", Area: "area_5", Client: "client_15", Note: "historical rollout note 32 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_033", Area: "area_6", Client: "client_16", Note: "historical rollout note 33 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_034", Area: "area_7", Client: "client_0", Note: "historical rollout note 34 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_035", Area: "area_8", Client: "client_1", Note: "historical rollout note 35 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_036", Area: "area_0", Client: "client_2", Note: "historical rollout note 36 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_037", Area: "area_1", Client: "client_3", Note: "historical rollout note 37 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_038", Area: "area_2", Client: "client_4", Note: "historical rollout note 38 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_039", Area: "area_3", Client: "client_5", Note: "historical rollout note 39 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_040", Area: "area_4", Client: "client_6", Note: "historical rollout note 40 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_041", Area: "area_5", Client: "client_7", Note: "historical rollout note 41 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_042", Area: "area_6", Client: "client_8", Note: "historical rollout note 42 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_043", Area: "area_7", Client: "client_9", Note: "historical rollout note 43 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_044", Area: "area_8", Client: "client_10", Note: "historical rollout note 44 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_045", Area: "area_0", Client: "client_11", Note: "historical rollout note 45 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_046", Area: "area_1", Client: "client_12", Note: "historical rollout note 46 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_047", Area: "area_2", Client: "client_13", Note: "historical rollout note 47 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_048", Area: "area_3", Client: "client_14", Note: "historical rollout note 48 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_049", Area: "area_4", Client: "client_15", Note: "historical rollout note 49 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_050", Area: "area_5", Client: "client_16", Note: "historical rollout note 50 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_051", Area: "area_6", Client: "client_0", Note: "historical rollout note 51 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_052", Area: "area_7", Client: "client_1", Note: "historical rollout note 52 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_053", Area: "area_8", Client: "client_2", Note: "historical rollout note 53 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_054", Area: "area_0", Client: "client_3", Note: "historical rollout note 54 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_055", Area: "area_1", Client: "client_4", Note: "historical rollout note 55 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_056", Area: "area_2", Client: "client_5", Note: "historical rollout note 56 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_057", Area: "area_3", Client: "client_6", Note: "historical rollout note 57 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_058", Area: "area_4", Client: "client_7", Note: "historical rollout note 58 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_059", Area: "area_5", Client: "client_8", Note: "historical rollout note 59 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_060", Area: "area_6", Client: "client_9", Note: "historical rollout note 60 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_061", Area: "area_7", Client: "client_10", Note: "historical rollout note 61 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_062", Area: "area_8", Client: "client_11", Note: "historical rollout note 62 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_063", Area: "area_0", Client: "client_12", Note: "historical rollout note 63 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_064", Area: "area_1", Client: "client_13", Note: "historical rollout note 64 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_065", Area: "area_2", Client: "client_14", Note: "historical rollout note 65 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_066", Area: "area_3", Client: "client_15", Note: "historical rollout note 66 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_067", Area: "area_4", Client: "client_16", Note: "historical rollout note 67 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_068", Area: "area_5", Client: "client_0", Note: "historical rollout note 68 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_069", Area: "area_6", Client: "client_1", Note: "historical rollout note 69 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_070", Area: "area_7", Client: "client_2", Note: "historical rollout note 70 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_071", Area: "area_8", Client: "client_3", Note: "historical rollout note 71 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_072", Area: "area_0", Client: "client_4", Note: "historical rollout note 72 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_073", Area: "area_1", Client: "client_5", Note: "historical rollout note 73 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_074", Area: "area_2", Client: "client_6", Note: "historical rollout note 74 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_075", Area: "area_3", Client: "client_7", Note: "historical rollout note 75 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_076", Area: "area_4", Client: "client_8", Note: "historical rollout note 76 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_077", Area: "area_5", Client: "client_9", Note: "historical rollout note 77 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_078", Area: "area_6", Client: "client_10", Note: "historical rollout note 78 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_079", Area: "area_7", Client: "client_11", Note: "historical rollout note 79 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_080", Area: "area_8", Client: "client_12", Note: "historical rollout note 80 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_081", Area: "area_0", Client: "client_13", Note: "historical rollout note 81 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_082", Area: "area_1", Client: "client_14", Note: "historical rollout note 82 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_083", Area: "area_2", Client: "client_15", Note: "historical rollout note 83 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_084", Area: "area_3", Client: "client_16", Note: "historical rollout note 84 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_085", Area: "area_4", Client: "client_0", Note: "historical rollout note 85 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_086", Area: "area_5", Client: "client_1", Note: "historical rollout note 86 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_087", Area: "area_6", Client: "client_2", Note: "historical rollout note 87 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_088", Area: "area_7", Client: "client_3", Note: "historical rollout note 88 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_089", Area: "area_8", Client: "client_4", Note: "historical rollout note 89 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_090", Area: "area_0", Client: "client_5", Note: "historical rollout note 90 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_091", Area: "area_1", Client: "client_6", Note: "historical rollout note 91 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_092", Area: "area_2", Client: "client_7", Note: "historical rollout note 92 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_093", Area: "area_3", Client: "client_8", Note: "historical rollout note 93 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_094", Area: "area_4", Client: "client_9", Note: "historical rollout note 94 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_095", Area: "area_5", Client: "client_10", Note: "historical rollout note 95 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_096", Area: "area_6", Client: "client_11", Note: "historical rollout note 96 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_097", Area: "area_7", Client: "client_12", Note: "historical rollout note 97 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_098", Area: "area_8", Client: "client_13", Note: "historical rollout note 98 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_099", Area: "area_0", Client: "client_14", Note: "historical rollout note 99 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_100", Area: "area_1", Client: "client_15", Note: "historical rollout note 100 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_101", Area: "area_2", Client: "client_16", Note: "historical rollout note 101 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_102", Area: "area_3", Client: "client_0", Note: "historical rollout note 102 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_103", Area: "area_4", Client: "client_1", Note: "historical rollout note 103 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_104", Area: "area_5", Client: "client_2", Note: "historical rollout note 104 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_105", Area: "area_6", Client: "client_3", Note: "historical rollout note 105 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_106", Area: "area_7", Client: "client_4", Note: "historical rollout note 106 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_107", Area: "area_8", Client: "client_5", Note: "historical rollout note 107 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_108", Area: "area_0", Client: "client_6", Note: "historical rollout note 108 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_109", Area: "area_1", Client: "client_7", Note: "historical rollout note 109 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_110", Area: "area_2", Client: "client_8", Note: "historical rollout note 110 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_111", Area: "area_3", Client: "client_9", Note: "historical rollout note 111 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_112", Area: "area_4", Client: "client_10", Note: "historical rollout note 112 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_113", Area: "area_5", Client: "client_11", Note: "historical rollout note 113 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_114", Area: "area_6", Client: "client_12", Note: "historical rollout note 114 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_115", Area: "area_7", Client: "client_13", Note: "historical rollout note 115 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_116", Area: "area_8", Client: "client_14", Note: "historical rollout note 116 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_117", Area: "area_0", Client: "client_15", Note: "historical rollout note 117 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_118", Area: "area_1", Client: "client_16", Note: "historical rollout note 118 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_119", Area: "area_2", Client: "client_0", Note: "historical rollout note 119 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_120", Area: "area_3", Client: "client_1", Note: "historical rollout note 120 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_121", Area: "area_4", Client: "client_2", Note: "historical rollout note 121 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_122", Area: "area_5", Client: "client_3", Note: "historical rollout note 122 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_123", Area: "area_6", Client: "client_4", Note: "historical rollout note 123 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_124", Area: "area_7", Client: "client_5", Note: "historical rollout note 124 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_125", Area: "area_8", Client: "client_6", Note: "historical rollout note 125 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_126", Area: "area_0", Client: "client_7", Note: "historical rollout note 126 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_127", Area: "area_1", Client: "client_8", Note: "historical rollout note 127 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_128", Area: "area_2", Client: "client_9", Note: "historical rollout note 128 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_129", Area: "area_3", Client: "client_10", Note: "historical rollout note 129 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_130", Area: "area_4", Client: "client_11", Note: "historical rollout note 130 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_131", Area: "area_5", Client: "client_12", Note: "historical rollout note 131 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_132", Area: "area_6", Client: "client_13", Note: "historical rollout note 132 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_133", Area: "area_7", Client: "client_14", Note: "historical rollout note 133 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_134", Area: "area_8", Client: "client_15", Note: "historical rollout note 134 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_135", Area: "area_0", Client: "client_16", Note: "historical rollout note 135 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_136", Area: "area_1", Client: "client_0", Note: "historical rollout note 136 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_137", Area: "area_2", Client: "client_1", Note: "historical rollout note 137 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_138", Area: "area_3", Client: "client_2", Note: "historical rollout note 138 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_139", Area: "area_4", Client: "client_3", Note: "historical rollout note 139 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_140", Area: "area_5", Client: "client_4", Note: "historical rollout note 140 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_141", Area: "area_6", Client: "client_5", Note: "historical rollout note 141 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_142", Area: "area_7", Client: "client_6", Note: "historical rollout note 142 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_143", Area: "area_8", Client: "client_7", Note: "historical rollout note 143 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_144", Area: "area_0", Client: "client_8", Note: "historical rollout note 144 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_145", Area: "area_1", Client: "client_9", Note: "historical rollout note 145 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_146", Area: "area_2", Client: "client_10", Note: "historical rollout note 146 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_147", Area: "area_3", Client: "client_11", Note: "historical rollout note 147 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_148", Area: "area_4", Client: "client_12", Note: "historical rollout note 148 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_149", Area: "area_5", Client: "client_13", Note: "historical rollout note 149 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_150", Area: "area_6", Client: "client_14", Note: "historical rollout note 150 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_151", Area: "area_7", Client: "client_15", Note: "historical rollout note 151 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_152", Area: "area_8", Client: "client_16", Note: "historical rollout note 152 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_153", Area: "area_0", Client: "client_0", Note: "historical rollout note 153 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_154", Area: "area_1", Client: "client_1", Note: "historical rollout note 154 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_155", Area: "area_2", Client: "client_2", Note: "historical rollout note 155 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_156", Area: "area_3", Client: "client_3", Note: "historical rollout note 156 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_157", Area: "area_4", Client: "client_4", Note: "historical rollout note 157 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_158", Area: "area_5", Client: "client_5", Note: "historical rollout note 158 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_159", Area: "area_6", Client: "client_6", Note: "historical rollout note 159 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_160", Area: "area_7", Client: "client_7", Note: "historical rollout note 160 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_161", Area: "area_8", Client: "client_8", Note: "historical rollout note 161 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_162", Area: "area_0", Client: "client_9", Note: "historical rollout note 162 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_163", Area: "area_1", Client: "client_10", Note: "historical rollout note 163 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_164", Area: "area_2", Client: "client_11", Note: "historical rollout note 164 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_165", Area: "area_3", Client: "client_12", Note: "historical rollout note 165 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_166", Area: "area_4", Client: "client_13", Note: "historical rollout note 166 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_167", Area: "area_5", Client: "client_14", Note: "historical rollout note 167 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_168", Area: "area_6", Client: "client_15", Note: "historical rollout note 168 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_169", Area: "area_7", Client: "client_16", Note: "historical rollout note 169 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_170", Area: "area_8", Client: "client_0", Note: "historical rollout note 170 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_171", Area: "area_0", Client: "client_1", Note: "historical rollout note 171 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_172", Area: "area_1", Client: "client_2", Note: "historical rollout note 172 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_173", Area: "area_2", Client: "client_3", Note: "historical rollout note 173 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_174", Area: "area_3", Client: "client_4", Note: "historical rollout note 174 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_175", Area: "area_4", Client: "client_5", Note: "historical rollout note 175 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_176", Area: "area_5", Client: "client_6", Note: "historical rollout note 176 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_177", Area: "area_6", Client: "client_7", Note: "historical rollout note 177 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_178", Area: "area_7", Client: "client_8", Note: "historical rollout note 178 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_179", Area: "area_8", Client: "client_9", Note: "historical rollout note 179 for message delivery dashboards and migration checks"},
	{Name: "compat_rule_180", Area: "area_0", Client: "client_10", Note: "historical rollout note 180 for message delivery dashboards and migration checks"},
}

func RulesByArea(area string) []CompatRule {
	out := make([]CompatRule, 0)
	for _, r := range CompatCatalog {
		if r.Area == area { out = append(out, r) }
	}
	return out
}
